version: "3.3"

services:
  main:
    name: main
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    ports:
      - 5458:5458
    volumes:
      - ./static/:/opt/static/
    environment:
      DB_HOST: postgres
      DB_NAME: kinopoisk
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ddd-network

  postgres:
    image: postgres:17.0
    env_file:
      - .env
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - ./build/sql/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ddd-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      main:
        condition: service_started
    networks:
      - ddd-network

  telegram-notifier:
    image: lorcas/docker-telegram-notifier:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TELEGRAM_NOTIFIER_BOT_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_NOTIFIER_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_NOTIFIER_TOPIC_ID: ${TELEGRAM_TOPIC_ID}
    labels:
      telegram-notifier.monitor: false

volumes:
  postgres_data:

networks:
  ddd-network:
    name: ddd-network
    driver: bridge
