global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus" 
    static_configs:
      - targets: [ 'localhost:9090' ]
      
  - job_name: "node_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node_exporter:9100' ]
  
  - job_name: "main"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'main:5458' ]  

  - job_name: "films"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'films:5459' ]  

  - job_name: "auth"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'auth:5460' ]  
