name: Kinopoisk deploy

on:
  push:
    branches:
      - main  
      - develop # текущая ветка разработки
jobs:
  #ШАГ 1: прогон линтеров
  linters-act: #имя шага
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.7'
      - uses: actions/checkout@v3 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
  #ШАГ 2: прогон тестов
  tests-act:
    name: tests 
    needs: linters-act #если линтеры упали, дальше тесты не запускаются
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.7'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  #ШАГ 3: деплой 
  deploy:
    name: Deploy MyApp
    needs: tests-act #только после тестов и линитера
    runs-on: ubuntu-latest
    steps:
      - name: Pull code #обновляем код
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} #все данные лежат в секретах в репозитории
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2025_2_DavaiDavaiDeploy && git pull 
      - name: Build containers #собираем код
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2025_2_DavaiDavaiDeploy && sudo docker compose build
      - name: Restart service #рестартим код
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2025_2_DavaiDavaiDeploy && sudo docker compose down && sudo docker compose up -d #-d освобождает консоль