name: Kinopoisk deploy

on:
  push:
    branches:
      - main  
      - develop 
jobs:
  linters-act: 
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.7'
      - uses: actions/checkout@v3 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --disable-all -E staticcheck --skip-files=".*" --exclude="SA1019"

  deploy:
    name: Deploy MyApp
    timeout-minutes: 15
    timeout: 3 hours 30 minutes
    needs: linters-act 
    runs-on: ubuntu-latest
    steps:
      - name: Pull code 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2025_2_DavaiDavaiDeploy && git stash && git pull 
      - name: Build containers 
        uses: appleboy/ssh-action@master
        with:
          timeout: 25m
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2025_2_DavaiDavaiDeploy 
      - name: Restart service 
        uses: appleboy/ssh-action@master
        with:
          timeout: 25m
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2025_2_DavaiDavaiDeploy && sudo docker compose down -v && sudo docker compose up -d --build
